id: P002981
initial_creation_type: ocr
source_metadata:
  id: bdr:W2793
  title: གྲུབ་མཐའ་ཐུབ་བསྟན་ལྷུན་པོའི་མཛེས་རྒྱན
  author: ''
  volumes:
    a783c071d246436596d108b6ba8960f2:
      image_group_id: I1PD36290
      title: ''
      volume_number: 1
      total_pages: 622
      base_file: v001.txt
