id: IA914F1FF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T15:10:22+00:00'
last_modified: '2022-06-07T16:45:01.138559+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2793
  title: གྲུབ་མཐའ་ཐུབ་བསྟན་ལྷུན་པོའི་མཛེས་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    386E:
      image_group_id: I1PD36290
      title: ''
      total_pages: 622
      order: 1
      base_file: 386E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
